name: gag
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blas=1.0=mkl
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - certifi=2023.7.22=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.2=py310h22a60cf_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cython=3.0.0=py310h5eee18b_0
  - embree=4.2.0=habf647b_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - icu=72.1=hcb278e6_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jinja2=3.1.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.7.1.12=0
  - libcurand=10.3.3.129=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.1.0=he5830b7_0
  - libhwloc=2.9.2=nocuda_h7313eea_1008
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxml2=2.11.5=h0d562d8_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.6=py310h1128e8f_1
  - mkl_random=1.2.2=py310h1128e8f_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py310h06a4308_0
  - numexpr=2.8.4=py310h85018f9_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.10=h7f8727e_0
  - pandas=1.5.3=py310h1128e8f_0
  - pillow=9.4.0=py310h6a678d5_0
  - pip=23.2.1=py310h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyembree=0.1.6=py310h9b08913_3
  - pyopenssl=23.2.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.12=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.0.1=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py310h06a4308_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py310h06a4308_0
  - rocm-smi=5.6.0=h59595ed_1
  - setuptools=68.0.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.11.1=py310h06a4308_0
  - tbb=2021.10.0=h00ab1b0_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.0.2=py310_cu117
  - torchtriton=2.0.0=py310
  - torchvision=0.15.2=py310_cu117
  - typing_extensions=4.7.1=py310h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py310h06a4308_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_0
  - pip:
      - addict==2.4.0
      - ansi2html==1.8.0
      - appdirs==1.4.4
      - asttokens==2.2.1
      - attrs==23.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - burg-toolkit==0.3.0
      - chardet==5.2.0
      - click==8.1.6
      - colorlog==6.7.0
      - comm==0.1.4
      - configargparse==1.7
      - contourpy==1.1.0
      - cycler==0.11.0
      - dash==2.12.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - embreex==2.17.7.post1
      - executing==1.2.0
      - fastjsonschema==2.18.0
      - flask==2.2.5
      - fonttools==4.42.0
      - fpdf==1.7.2
      - freetype-py==2.4.0
      - gdown==4.7.1
      - gitdb==4.0.10
      - gitpython==3.1.32
      - h5py==3.9.0
      - imageio==2.31.1
      - ipython==8.14.0
      - ipywidgets==8.1.0
      - itsdangerous==2.1.2
      - jedi==0.19.0
      - joblib==1.3.2
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter-core==5.3.1
      - jupyterlab-widgets==3.0.8
      - kiwisolver==1.4.4
      - lazy-loader==0.3
      - llvmlite==0.40.1
      - lxml==4.9.3
      - mapbox-earcut==1.0.1
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - nbformat==5.7.0
      - nest-asyncio==1.5.7
      - numba==0.57.1
      - numpy==1.24.4
      - numpy-quaternion==2022.4.3
      - open3d==0.17.0
      - opencv-contrib-python==4.8.0.76
      - packaging==23.1
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==3.10.0
      - plotly==5.16.1
      - plyfile==1.0.1
      - prompt-toolkit==3.0.39
      - protobuf==4.24.0
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pybullet==3.2.5
      - pycollada==0.7.2
      - pyglet==2.0.9
      - pygments==2.16.1
      - pykdtree==1.3.7.post0
      - pyopengl==3.1.0
      - pyparsing==3.0.9
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - python-fcl==0.7.0.5
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - referencing==0.30.2
      - retrying==1.3.4
      - rpds-py==0.9.2
      - rtree==1.0.1
      - scikit-image==0.21.0
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - sentry-sdk==1.29.2
      - setproctitle==1.3.2
      - shapely==2.0.1
      - smmap==5.0.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - svg-path==6.3
      - tenacity==8.2.3
      - tensorboardx==2.6.2
      - threadpoolctl==3.2.0
      - tifffile==2023.8.12
      - torch-scatter==2.1.1+pt20cu117
      - tqdm==4.66.1
      - traitlets==5.9.0
      - trimesh==3.23.2
      - wandb==0.15.8
      - wcwidth==0.2.6
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.8
      - xxhash==3.3.0
prefix: /users/2/220251877/miniconda3/envs/gag
